{"name": "test_topupsaldo_success", "status": "failed", "statusDetails": {"message": "Failed: terdapat error selama pengujian yaitu: Message: \nStacktrace:\nNoSuchElementError: An element could not be located on the page using the given search parameters.\n    at AndroidUiautomator2Driver.findElOrEls (/Users/kevin/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)\n    at processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at AndroidUiautomator2Driver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\n    at AndroidUiautomator2Driver.findElement (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)", "trace": "driver = <appium.webdriver.webdriver.WebDriver (session=\"c6bf772d-375d-42f0-ba37-082167943586\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    @pytest.mark.run(order=3)\n    def test_topupsaldo_success(driver):\n        topupsaldo = TopUpSaldoPage(driver)\n        try:\n            logging.info('Mulai pengujian topup saldo')\n>           topupsaldo.click_menu_topupsaldo()\n\nsrc/tests/test_topupsaldo.py:15: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.topupsaldo_page.TopUpSaldoPage object at 0x10a226c20>\n\n    def click_menu_topupsaldo(self):\n>       topupsaldo_button = WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((AppiumBy.ID, 'com.mkpmobile.retail.mitramint:id/containerTopupSaldo')))\n\nsrc/pages/topupsaldo_page.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <selenium.webdriver.support.wait.WebDriverWait (session=\"c6bf772d-375d-42f0-ba37-082167943586\")>\nmethod = <function element_to_be_clickable.<locals>._predicate at 0x10a2d44c0>, message = ''\n\n    def until(self, method: Callable[[D], Union[Literal[False], T]], message: str = \"\") -> T:\n        \"\"\"Calls the method provided with the driver as an argument until the \\\n        return value does not evaluate to ``False``.\n    \n        :param method: callable(WebDriver)\n        :param message: optional message for :exc:`TimeoutException`\n        :returns: the result of the last call to `method`\n        :raises: :exc:`selenium.common.exceptions.TimeoutException` if timeout occurs\n        \"\"\"\n        screen = None\n        stacktrace = None\n    \n        end_time = time.monotonic() + self._timeout\n        while True:\n            try:\n                value = method(self._driver)\n                if value:\n                    return value\n            except self._ignored_exceptions as exc:\n                screen = getattr(exc, \"screen\", None)\n                stacktrace = getattr(exc, \"stacktrace\", None)\n            time.sleep(self._poll)\n            if time.monotonic() > end_time:\n                break\n>       raise TimeoutException(message, screen, stacktrace)\nE       selenium.common.exceptions.TimeoutException: Message: \nE       Stacktrace:\nE       NoSuchElementError: An element could not be located on the page using the given search parameters.\nE           at AndroidUiautomator2Driver.findElOrEls (/Users/kevin/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)\nE           at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE           at AndroidUiautomator2Driver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\nE           at AndroidUiautomator2Driver.findElement (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n\nvenv/lib/python3.10/site-packages/selenium/webdriver/support/wait.py:105: TimeoutException\n\nDuring handling of the above exception, another exception occurred:\n\ndriver = <appium.webdriver.webdriver.WebDriver (session=\"c6bf772d-375d-42f0-ba37-082167943586\")>\n\n    @pytest.mark.usefixtures(\"driver\")\n    @pytest.mark.run(order=3)\n    def test_topupsaldo_success(driver):\n        topupsaldo = TopUpSaldoPage(driver)\n        try:\n            logging.info('Mulai pengujian topup saldo')\n            topupsaldo.click_menu_topupsaldo()\n            topupsaldo.method_payment()\n            topupsaldo.QRIS_payment()\n            topupsaldo.click_pilih_list_payment()\n            topupsaldo.input_nominal()\n            topupsaldo.click_button_lanjut()\n            topupsaldo.click_button_lanjut_inquiry()\n            topupsaldo.wait_for_qris()\n            topupsaldo.wait_for_payment_success()\n            topupsaldo.click_button_print_struk()\n            topupsaldo.click_button_back()\n            topupsaldo.click_button_back_home()\n            topupsaldo.wait_for_home_page()\n            logging.info('Topup saldo berhasil')\n        except Exception as e:\n            logging.error(f'Terdapat error selama pengujian yaitu: {e}')\n>           pytest.fail(f'terdapat error selama pengujian yaitu: {e}')\nE           Failed: terdapat error selama pengujian yaitu: Message: \nE           Stacktrace:\nE           NoSuchElementError: An element could not be located on the page using the given search parameters.\nE               at AndroidUiautomator2Driver.findElOrEls (/Users/kevin/.appium/node_modules/appium-uiautomator2-driver/node_modules/appium-android-driver/lib/commands/find.ts:86:11)\nE               at processTicksAndRejections (node:internal/process/task_queues:95:5)\nE               at AndroidUiautomator2Driver.findElOrElsWithProcessing (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:60:12)\nE               at AndroidUiautomator2Driver.findElement (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands/find.ts:75:12)\n\nsrc/tests/test_topupsaldo.py:31: Failed"}, "attachments": [{"name": "log", "source": "9559ab95-11a0-4cb6-acc3-d677e15abcf1-attachment.txt", "type": "text/plain"}], "start": 1727340689949, "stop": 1727340700368, "uuid": "2c0d6a9c-7b11-4f9c-b396-120b93c54476", "historyId": "df2ceb00f61e7c4f65e8f4d7f46ad13b", "testCaseId": "b4452571540d0222bec811b5e355dbbe", "fullName": "src.tests.test_topupsaldo#test_topupsaldo_success", "labels": [{"name": "tag", "value": "run(order=3)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('driver')"}, {"name": "parentSuite", "value": "src.tests"}, {"name": "suite", "value": "test_topupsaldo"}, {"name": "host", "value": "macbooks-MacBook-Air.local"}, {"name": "thread", "value": "40083-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "src.tests.test_topupsaldo"}]}