{"uid":"31800456da5efe06","name":"test_login_success","fullName":"src.tests.test_login#test_login_success","historyId":"d7250828c2bc668cfe9858cb88b836ce","time":{"start":1727337128959,"stop":1727337142502,"duration":13543},"status":"passed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":42,"retriesStatusChange":true,"beforeStages":[{"name":"driver","time":{"start":1727337114980,"stop":1727337128952,"duration":13972},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"driver::0","time":{"start":1727337186438,"stop":1727337187212,"duration":774},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"run(order=1)"},{"name":"tag","value":"@pytest.mark.usefixtures('driver')"},{"name":"parentSuite","value":"src.tests"},{"name":"suite","value":"test_login"},{"name":"host","value":"macbooks-MacBook-Air.local"},{"name":"thread","value":"39037-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"src.tests.test_login"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"46781f41aac4642b","status":"passed","time":{"start":1727334332014,"stop":1727334346054,"duration":14040}},{"uid":"3cad472f6175bebe","status":"passed","time":{"start":1727262534659,"stop":1727262548599,"duration":13940}},{"uid":"dada68726e1c89e0","status":"passed","time":{"start":1727253775909,"stop":1727253790838,"duration":14929}},{"uid":"e5127e3d8521a5a9","status":"passed","time":{"start":1727251491101,"stop":1727251506238,"duration":15137}},{"uid":"558425240d92da0","status":"passed","time":{"start":1727251325695,"stop":1727251338356,"duration":12661}},{"uid":"a5d46dda112dcc29","status":"passed","time":{"start":1727251092073,"stop":1727251105713,"duration":13640}},{"uid":"445debd17e5c001c","status":"passed","time":{"start":1727250964567,"stop":1727250979197,"duration":14630}},{"uid":"513b7ff5cc549ac9","status":"passed","time":{"start":1727250434273,"stop":1727250448665,"duration":14392}},{"uid":"a42be5f641a8f22d","status":"passed","time":{"start":1727250219049,"stop":1727250232168,"duration":13119}},{"uid":"d59ea9c280d66f38","status":"passed","time":{"start":1727249946750,"stop":1727249959318,"duration":12568}},{"uid":"f77663aac1222787","status":"passed","time":{"start":1727249709250,"stop":1727249724331,"duration":15081}},{"uid":"2985659923628ed6","status":"passed","time":{"start":1727249618628,"stop":1727249632565,"duration":13937}},{"uid":"668ed92776707f8a","status":"passed","time":{"start":1727169933833,"stop":1727169946931,"duration":13098}},{"uid":"57688dd0d23f76c7","status":"passed","time":{"start":1727169490119,"stop":1727169503605,"duration":13486}},{"uid":"25eae0affe5d7f35","status":"passed","time":{"start":1727169384866,"stop":1727169397961,"duration":13095}},{"uid":"c8f0ddda8dc1d75b","status":"passed","time":{"start":1727169230009,"stop":1727169243699,"duration":13690}},{"uid":"85aaab5cbbf9a206","status":"passed","time":{"start":1727169046559,"stop":1727169060538,"duration":13979}},{"uid":"157053b428aa09c5","status":"passed","time":{"start":1727168004118,"stop":1727168018461,"duration":14343}},{"uid":"6348f990867c5d87","status":"passed","time":{"start":1727167801566,"stop":1727167815405,"duration":13839}},{"uid":"796034ab21726495","status":"passed","time":{"start":1727167024259,"stop":1727167037539,"duration":13280}},{"uid":"2d73033dceba27d4","status":"passed","time":{"start":1727166335790,"stop":1727166349483,"duration":13693}},{"uid":"537e0946a8292adc","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/Users/kevin/Library/Android/sdk/platform-tools/adb -P 5037 -s 1902390100180748 shell getprop ro.build.version.sdk' exited with code 1'; Command output: adb: device '1902390100180748' not found\n\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: Error getting device API level. Original error: Error executing adbExec. Original error: 'Command '/Users/kevin/Library/Android/sdk/platform-tools/adb -P 5037 -s 1902390100180748 shell getprop ro.build.version.sdk' exited with code 1'; Command output: adb: device '1902390100180748' not found\n\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)","time":{"start":1727166236741,"stop":1727166236741,"duration":0}},{"uid":"9f6861dbf2c7c371","status":"passed","time":{"start":1727165435291,"stop":1727165447762,"duration":12471}},{"uid":"65da18194c50151f","status":"passed","time":{"start":1727164879173,"stop":1727164892083,"duration":12910}},{"uid":"88f49b5d999afeca","status":"passed","time":{"start":1727164693779,"stop":1727164707401,"duration":13622}},{"uid":"7e4fbefd3217a23d","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x110161f00>: Failed to establish a new connection: [Errno 61] Connection refused'))","time":{"start":1727164629130,"stop":1727164629130,"duration":0}},{"uid":"7554ecca2b6b7daf","status":"passed","time":{"start":1727083445668,"stop":1727083459099,"duration":13431}},{"uid":"856afa8a8a37feab","status":"passed","time":{"start":1727083348883,"stop":1727083362755,"duration":13872}},{"uid":"283a7705cf0108ff","status":"passed","time":{"start":1727083244843,"stop":1727083259143,"duration":14300}},{"uid":"88af1b1c57ea8cd","status":"passed","time":{"start":1727083176702,"stop":1727083190525,"duration":13823}},{"uid":"bcee54124d08509f","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)","time":{"start":1727082958942,"stop":1727082958942,"duration":0}},{"uid":"c2db8037cfcd9a1","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)","time":{"start":1727082899736,"stop":1727082899736,"duration":0}},{"uid":"ec56ddccd99ae807","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)","time":{"start":1727082852938,"stop":1727082852938,"duration":0}},{"uid":"e2add30ae96f17ca","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\nStacktrace:\nUnknownError: An unknown server-side error occurred while processing the command. Original error: The application at '/Users/kevin/automated-testing/Apps2pay/MINT/MINT_Loket/src/app/LOKET MINT_1.24.06.02_Production.apk' does not exist or is not accessible\n    at getResponseForW3CError (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/errors.js:1145:9)\n    at asyncHandler (/usr/local/lib/node_modules/appium/node_modules/@appium/base-driver/lib/protocol/protocol.js:485:57)","time":{"start":1727082750124,"stop":1727082750124,"duration":0}},{"uid":"21194fd96a37724e","status":"passed","time":{"start":1726741881308,"stop":1726741894863,"duration":13555}},{"uid":"a43c9f01701f663a","status":"passed","time":{"start":1726741710796,"stop":1726741724540,"duration":13744}},{"uid":"36dbf713e10c1923","status":"passed","time":{"start":1726741051391,"stop":1726741065632,"duration":14241}},{"uid":"6b116693dc7a796c","status":"passed","time":{"start":1726740598914,"stop":1726740611828,"duration":12914}},{"uid":"c7c1ebabbd9773ea","status":"passed","time":{"start":1726740105975,"stop":1726740119518,"duration":13543}},{"uid":"b57c68baec8a2c6","status":"passed","time":{"start":1726739544438,"stop":1726739557863,"duration":13425}},{"uid":"78864ed5e70c7c83","status":"passed","time":{"start":1726739401641,"stop":1726739416406,"duration":14765}},{"uid":"472ecd549b1318","status":"passed","time":{"start":1726731017166,"stop":1726731031425,"duration":14259}}],"categories":[],"tags":["run(order=1)","@pytest.mark.usefixtures('driver')"]},"source":"31800456da5efe06.json","parameterValues":[]}